- .buildscript/deploy_snapshot.sh
- .buildscript/settings.xml
- .travis.yml
- README.md
- pom.xml
> Snapshots autodeploy

- CHANGELOG.md
- pom.xml
- src/main/java/com/contentful/java/cma/ModuleAssets.java
- src/main/java/com/contentful/java/cma/ModuleContentTypes.java
- src/main/java/com/contentful/java/cma/ModuleEntries.java
- src/main/java/com/contentful/java/cma/ServiceAssets.java
- src/main/java/com/contentful/java/cma/ServiceContentTypes.java
- src/main/java/com/contentful/java/cma/ServiceEntries.java
- src/test/kotlin/com/contentful/java/cma/AndroidTests.kt
- src/test/kotlin/com/contentful/java/cma/AssetTests.kt
- src/test/kotlin/com/contentful/java/cma/BaseTest.kt
- src/test/kotlin/com/contentful/java/cma/ClientTests.kt
- src/test/kotlin/com/contentful/java/cma/ContentTypeTests.kt
- src/test/kotlin/com/contentful/java/cma/EntryTests.kt
- src/test/kotlin/com/contentful/java/cma/GeneralTests.kt
- src/test/kotlin/com/contentful/java/cma/ModuleTests.kt
- src/test/kotlin/com/contentful/java/cma/SpaceTests.kt
- src/test/kotlin/com/contentful/java/cma/lib/TestCallback.kt
- src/test/kotlin/com/contentful/java/cma/lib/TestUtils.kt
> Support search queries

- src/main/java/com/contentful/java/cma/CMAClient.java
- src/main/java/com/contentful/java/cma/Constants.java
- src/main/java/com/contentful/java/cma/EntrySerializer.java
- src/test/kotlin/com/contentful/java/cma/EntryTests.kt
- src/test/resources/entry_create_links_request.json
> Convert included resources to links

- CHANGELOG.md
- src/main/java/com/contentful/java/cma/CMAClient.java
- src/main/java/com/contentful/java/cma/ModulePersonalAccessTokens.java
- src/main/java/com/contentful/java/cma/ServicePersonalAccessTokens.java
- src/main/java/com/contentful/java/cma/model/CMAPersonalAccessToken.java
- src/main/java/com/contentful/java/cma/model/CMAType.java
- src/test/bash/personal_access_token_create.sh
- src/test/bash/personal_access_token_create_error.sh
- src/test/bash/personal_access_token_get_all.sh
- src/test/bash/personal_access_token_get_one.sh
- src/test/bash/personal_access_token_revoke.sh
- src/test/kotlin/com/contentful/java/cma/PersonalAccessTokenTests.kt
- src/test/resources/personal_access_token_create.json
- src/test/resources/personal_access_token_create_error.json
- src/test/resources/personal_access_token_get_all.json
- src/test/resources/personal_access_token_get_one.json
- src/test/resources/personal_access_token_revoke.json
Adding [Personal Access Token](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/personal-access-tokens) ...
> Add personal access token api

- CHANGELOG.md
- src/main/java/com/contentful/java/cma/CMAClient.java
- src/main/java/com/contentful/java/cma/ModuleEditorInterfaces.java
- src/main/java/com/contentful/java/cma/ServiceEditorInterfaces.java
- src/main/java/com/contentful/java/cma/model/CMAEditorInterface.java
- src/main/java/com/contentful/java/cma/model/CMAType.java
- src/test/bash/editor_interfaces_get.sh
- src/test/bash/editor_interfaces_update.sh
- src/test/kotlin/com/contentful/java/cma/EditorInterfacesTests.kt
- src/test/resources/editor_interfaces_get.json
- src/test/resources/editor_interfaces_update.json
- src/test/resources/editor_interfaces_update_payload.json
See [Contentful Docs](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/editor-interface) for more details.
> add editor interface

- CHANGELOG.md
- src/main/java/com/contentful/java/cma/ModuleContentTypes.java
- src/main/java/com/contentful/java/cma/ModuleEntries.java
- src/main/java/com/contentful/java/cma/ServiceContentTypes.java
- src/main/java/com/contentful/java/cma/ServiceEntries.java
- src/main/java/com/contentful/java/cma/model/CMASnapshot.java
- src/main/java/com/contentful/java/cma/model/CMAType.java
- src/test/bash/content_type_snapshots_get_all.sh
- src/test/bash/content_type_snapshots_get_one.sh
- src/test/bash/entry_snapshots_get_all.sh
- src/test/bash/entry_snapshots_get_one.sh
- src/test/kotlin/com/contentful/java/cma/ContentTypeTests.kt
- src/test/kotlin/com/contentful/java/cma/EntryTests.kt
- src/test/resources/content_type_snapshots_get_all.json
- src/test/resources/content_type_snapshots_get_one.json
- src/test/resources/entry_snapshots_get_all.json
- src/test/resources/entry_snapshots_get_one.json
see https://www.contentful.com/developers/docs/references/content-management-api/#/reference/snapshots/entry-snapshots-collection
> Add snapshot endpoints

- CHANGELOG.md
- src/main/java/com/contentful/java/cma/ModuleApiKeys.java
- src/main/java/com/contentful/java/cma/ModuleOrganizations.java
- src/main/java/com/contentful/java/cma/ModulePersonalAccessTokens.java
- src/main/java/com/contentful/java/cma/ModuleRoles.java
- src/main/java/com/contentful/java/cma/ModuleSpaceMemberships.java
- src/main/java/com/contentful/java/cma/ModuleUiExtensions.java
- src/main/java/com/contentful/java/cma/ModuleWebhooks.java
- src/main/java/com/contentful/java/cma/ServiceApiKeys.java
- src/main/java/com/contentful/java/cma/ServiceOrganizations.java
- src/main/java/com/contentful/java/cma/ServicePersonalAccessTokens.java
- src/main/java/com/contentful/java/cma/ServiceRoles.java
- src/main/java/com/contentful/java/cma/ServiceSpaceMemberships.java
- src/main/java/com/contentful/java/cma/ServiceUiExtensions.java
- src/main/java/com/contentful/java/cma/ServiceWebhooks.java
- src/test/kotlin/com/contentful/java/cma/ApiKeysTests.kt
- src/test/kotlin/com/contentful/java/cma/OrganizationTests.kt
- src/test/kotlin/com/contentful/java/cma/PersonalAccessTokenTests.kt
- src/test/kotlin/com/contentful/java/cma/RolesTests.kt
- src/test/kotlin/com/contentful/java/cma/SpaceMembershipTests.kt
- src/test/kotlin/com/contentful/java/cma/UiExtensionsTests.kt
- src/test/kotlin/com/contentful/java/cma/WebhookTests.kt
> Add query parameter to all collection endpoints

- CHANGELOG.md
- src/main/java/com/contentful/java/cma/CMAClient.java
- src/main/java/com/contentful/java/cma/interceptor/RateLimitInterceptor.java
- src/main/java/com/contentful/java/cma/interceptor/RateLimitsListener.java
- src/main/java/com/contentful/java/cma/model/CMAHttpException.java
- src/main/java/com/contentful/java/cma/model/RateLimits.java
- src/test/kotlin/com/contentful/java/cma/ClientTests.kt
- src/test/kotlin/com/contentful/java/cma/HttpExceptionTests.kt
- src/test/kotlin/com/contentful/java/cma/interceptor/RateLimitsTests.kt
Create a RateLimitListener and register it to the client to get informed about rate limit headers.
> Add rate limit headers

- CHANGELOG.md
- README.md
- src/main/java/com/contentful/java/cma/model/CMAHttpException.java
- src/test/bash/content_type_error_field_type_invalid.sh
- src/test/bash/entry_create_error_array_type_value.sh
- src/test/kotlin/com/contentful/java/cma/ContentTypeTests.kt
- src/test/kotlin/com/contentful/java/cma/EntryTests.kt
- src/test/resources/content_type_error_field_type_invalid.json
- src/test/resources/entry_create_error_array_type_value.json
> fix: add value and expected to error body response

- CHANGELOG.md
- pom.xml
- src/main/java/com/contentful/java/cma/RxExtensions.java
- src/main/java/com/contentful/java/cma/model/CMAConstraint.java
- src/main/java/com/contentful/java/cma/model/CMAHttpException.java
- src/main/java/com/contentful/java/cma/model/CMANotWithEnvironmentsException.java
- src/main/java/com/contentful/java/cma/model/rich/CMARichHyperLink.java
- src/main/java/com/contentful/java/cma/model/rich/CMARichNode.java
- src/test/kotlin/com/contentful/java/cma/CMAHttpExceptionTest.kt
- src/test/kotlin/com/contentful/java/cma/ModelTests.kt
- src/test/kotlin/com/contentful/java/cma/RichFieldTests.kt
- src/test/kotlin/com/contentful/java/cma/e2e/RichTextE2E.kt
Updating fields using rich text fields should be enabled again.
> Fix rich text updating

- CHANGELOG.md
- README.md
- src/main/java/com/contentful/java/cma/model/rich/CMARichMark.java
- src/test/kotlin/com/contentful/java/cma/e2e/RichTextE2E.kt
adding rich text marks to address #115 .
> add rich text marks

- .gitignore
- CHANGELOG.md
- README.md
- src/main/java/com/contentful/java/cma/model/CMAUiExtension.java
- src/main/java/com/contentful/java/cma/model/CMAUiExtensionParameter.java
- src/main/java/com/contentful/java/cma/model/CMAUiExtensionParameterType.java
- src/main/java/com/contentful/java/cma/model/CMAUiExtensionParameters.java
- src/test/bash/ui_extensions_create_parameters.sh
- src/test/kotlin/com/contentful/java/cma/UiExtensionsTests.kt
- src/test/resources/ui_extensions_create_with_parameters.json
- Add [configuration](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/ui-extensions/configuration-parameters) to UI extensions
> Add configuration parameters to UI extensions

- src/main/java/com/contentful/java/cma/model/CMAUiExtension.java
- src/main/java/com/contentful/java/cma/model/CMAUiExtensionParameter.java
- src/main/java/com/contentful/java/cma/model/CMAUiExtensionParameters.java
- Fix javadoc issue
- Include javadoc generation in Travis script so we cannot merge PRs with errors
> Fix javadoc errors

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/contentful/java/cma/ModuleApiKeys.java
- src/main/java/com/contentful/java/cma/ModuleAssets.java
- src/main/java/com/contentful/java/cma/ModuleContentTypes.java
- src/main/java/com/contentful/java/cma/ModuleEditorInterfaces.java
- src/main/java/com/contentful/java/cma/ModuleEntries.java
- src/main/java/com/contentful/java/cma/ModuleEnvironments.java
- src/main/java/com/contentful/java/cma/ModuleLocales.java
- src/main/java/com/contentful/java/cma/ModuleOrganizations.java
- src/main/java/com/contentful/java/cma/ModulePersonalAccessTokens.java
- src/main/java/com/contentful/java/cma/ModulePreviewApiKeys.java
- src/main/java/com/contentful/java/cma/ModuleRoles.java
- src/main/java/com/contentful/java/cma/ModuleSpaceMemberships.java
- src/main/java/com/contentful/java/cma/ModuleSpaces.java
- src/main/java/com/contentful/java/cma/ModuleUiExtensions.java
- src/main/java/com/contentful/java/cma/ModuleUploads.java
- src/main/java/com/contentful/java/cma/ModuleUsers.java
- src/main/java/com/contentful/java/cma/ModuleWebhooks.java
- src/main/java/com/contentful/java/cma/RxExtensions.java
- src/main/java/com/contentful/java/cma/gson/FieldTypeAdapter.java
final keyword was deleted from the model classes, so that clients will be able to mock it for testing purpose.
> Remove final keyword from the classes to ensure testability

- checkstyle.xml
- pom.xml
Update checkstyle plugin version, fix checkstyle.xml issues
> Update checkstyle version and fix checkstyle.xml configuration

- src/main/java/com/contentful/java/cma/model/CMASystem.java
- src/test/kotlin/com/contentful/java/cma/SpaceTests.kt
- src/test/resources/space_fetch_all_response.json
- src/test/resources/space_fetch_one_response.json
> Support to fetch organization data when fetching CMASpace entities

- src/main/java/com/contentful/java/cma/model/CMAHttpException.java
Fixes: https://github.com/contentful/contentful-management.java/issues/138
> fix: call super() method of CMAHttpException

- src/main/java/com/contentful/java/cma/model/CMAAsset.java
- src/test/kotlin/com/contentful/java/cma/ModelTests.kt
Adding `metadata` field to the `CMAAsset`. This should fix https://github.com/contentful/contentful-management.java/issues/184
> feat: Add metadata field to the CMAAsset

- README.md
- src/main/java/com/contentful/java/cma/CMAClient.java
- src/main/java/com/contentful/java/cma/ModuleScheduledActions.java
- src/main/java/com/contentful/java/cma/ServiceScheduledActions.java
- src/main/java/com/contentful/java/cma/gson/CMASystemDeserializer.java
- src/main/java/com/contentful/java/cma/model/CMAArray.java
- src/main/java/com/contentful/java/cma/model/CMAPages.java
- src/main/java/com/contentful/java/cma/model/CMAScheduledAction.java
- src/main/java/com/contentful/java/cma/model/CMAScheduledActionStatus.java
- src/main/java/com/contentful/java/cma/model/CMAScheduledFor.java
- src/main/java/com/contentful/java/cma/model/CMASystem.java
- src/main/java/com/contentful/java/cma/model/CMAType.java
- src/test/kotlin/com/contentful/java/cma/ScheduledActionsTests.kt
- src/test/resources/bulk_actions_response.json
- src/test/resources/scheduled_action_cancel_response.json
- src/test/resources/scheduled_action_create_response.json
- src/test/resources/scheduled_action_fetch_response.json
- src/test/resources/scheduled_action_update_response.json
Implemented the ability to create, fetch, update, and delete scheduled actions.
> feat: Add support for scheduled actions

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/contentful/java/cma/CMAClient.java
- src/main/java/com/contentful/java/cma/ModuleTaxonomy.java
- src/main/java/com/contentful/java/cma/ServiceTaxonomy.java
- src/main/java/com/contentful/java/cma/model/CMAConcept.java
- src/main/java/com/contentful/java/cma/model/CMAConceptScheme.java
- src/main/java/com/contentful/java/cma/model/CMAContentType.java
- src/main/java/com/contentful/java/cma/model/CMAMetadata.java
- src/main/java/com/contentful/java/cma/model/CMATotalConcepts.java
- src/main/java/com/contentful/java/cma/model/CMAType.java
- src/test/kotlin/com/contentful/java/cma/TaxonomyTests.kt
- src/test/resources/taxonomy_concept_scheme_get_all_response.json
- src/test/resources/taxonomy_concept_scheme_get_one_response.json
- src/test/resources/taxonomy_concepts_create_one_response.json
- src/test/resources/taxonomy_concepts_get_all_response.json
- src/test/resources/taxonomy_concepts_get_one_response.json
This will add support for the Taxonomy API - https://www.contentful.com/developers/docs/references/content-management-api/#/reference/taxonomy
> feat: Add support for taxonomy API

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/contentful/java/cma/CMAClient.java
- src/main/java/com/contentful/java/cma/interceptor/ErrorInterceptor.java
- src/main/java/com/contentful/java/cma/model/CMAHttpException.java
- src/test/kotlin/com/contentful/java/cma/ModelTests.kt
- src/test/kotlin/com/contentful/java/cma/e2e/Base.kt
Added `logSensitiveData` flag to prevent logging retrofit headers.
> feat: Add logging sensitive data flag

- src/main/java/com/contentful/java/cma/ModuleEntries.java
- src/main/java/com/contentful/java/cma/ServiceEntries.java
- src/test/kotlin/com/contentful/java/cma/EntryTests.kt
- src/test/kotlin/com/contentful/java/cma/e2e/EntryE2E.kt
Added locale-based publishing as per request in this issue: https://github.com/contentful/contentful-management.java/issues/194
> feat: Add locale based publishing

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/contentful/java/cma/gson/MetadataSerializer.java
This will fix the issue with updating entries with taxonomy field.
> fix: Serialize taxonomies
